# values.yaml

image:
  repository: your-repo/vault-secrets-exporter
  pullPolicy: IfNotPresent
  tag: "latest"

vault:
  address: "http://vault.default.svc.cluster.local:8200"
  kvMountPath: "secret"
  namespace: "" # Optional: for Vault Enterprise

# NEW: Authentication configuration
auth:
  # Method can be 'token' or 'approle'
  method: token
  
  # Configuration for 'token' method
  token:
    # The name of an existing K8s secret containing the Vault token.
    # The secret must have a key named 'token'.
    existingSecretName: "vault-token"

  # Configuration for 'approle' method
  approle:
    # The name of an existing K8s secret containing the RoleID and SecretID.
    # The secret must have keys named 'role_id' and 'secret_id'.
    existingSecretName: "vault-approle-credentials"

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 9102
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"

resources: {}